### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by YanaHontarenko** [liuch37/sar-pytorch#1]
How many time do you need to train this model? On GPU/CPU?

**Comment by liuch37** [comment]
It depends on the dataset size. But generally it is pretty fast, I use one gpu.

**Comment by YanaHontarenko** [comment]
@liuch37 Of course I understand that training time depends on dataset size. 
I just want to unserstand how many time do you need to take metrics which you show in this repo

For example, in case with SVT dataset.
