### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by YanaHontarenko** [liuch37/sar-pytorch#2]
Hello!

I have to notice that you create great work! Code is easy to read and use!

But I have issue about **Syn90k** and **SynthText**. 
Both of this datasets after loading haven't folder named _train_ or _test_. Did you provide some scripts for preparing this datasets into required form? Because I downloaded them with links which you provided and it aren't in required form.

Or maybe you can share some info which can help me with preparing.

**Comment by liuch37** [comment]
For these two datasets you need to split them into train/test folders yourself with your own splitting strategy. You can refer to line 81 in train.py to see how it is handled for different datasets.

**Comment by YanaHontarenko** [comment]
Thank you for the answer.
