### ISSUE TITLE
train on my own dataset

### ISSUE THREAD

**Issue by summer-1010** [liuch37/sar-pytorch#7]
@liuch37 hi!I have checked your great code and i found that you said it just support svt,iiit5k,syn90k and synthtext datasets.If i wanna train my own dataset could i just need to make my data just like one of thoses supported datasets forms?

**Comment by liuch37** [comment]
Yes, definitely you can. That is a good strategy.

**Comment by summer-1010** [comment]
@liuch37 thanks!I will try!!

**Comment by summer-1010** [comment]
![image](https://user-images.githubusercontent.com/72547452/125058962-53c5f600-e09a-11eb-8280-ad7e050ba2d1.png)

@liuch37 sorry to bother you again, I had faced some problems when i am trying to start training.I found that the num of labels is 97(output_classes),and the seq_len is 40,if my own data's labels is 283 what should i set seq_len.Maybe same as the len of label?

**Comment by summer-1010** [comment]
after i change the seq_len and start to train, i still got error 'CUDA out of memory' even when i set batchsize to 1

**Comment by liuch37** [comment]
What does 283 mean? seq_len means maximal characters in one image.

**Comment by summer-1010** [comment]
@liuch37 my data got 283 classes of label in total ,i haven't count the maximal characters in one image,could i just set it to the max(283)

**Comment by liuch37** [comment]
In this case you may want to write your own dictionary_generator in ```train.py```.  283 is the number of output classes. seq_len=40 is pretty long already, try to reduce it if you still face OOM problem.
```
voc, char2id, id2char = dictionary_generator()
output_classes = len(voc)
```

**Comment by summer-1010** [comment]
@liuch37 thanks again! I will try it .

**Comment by summer-1010** [comment]
![image](https://user-images.githubusercontent.com/72547452/125185261-77f91280-e213-11eb-8656-f63812ea7475.png)
@liuch37 I can run it successfully if i seq_len = 283,if i reduce it to 30 or forty i will meet the erroe above as the picture show.
